[package]
name = "do-not-publish/xyz"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
Maid = "nightcycle/maid@2.0.0"
ColdFusion8 = "nightcycle/cold-fusion@9.1.1"
InputHandler = "krungkualalumpur/inputhandler@0.1.2"
Sintesa = "krungkualalumpur/sintesa@0.2.1"
MathUtil = "krungkualalumpur/mathutil@0.1.3"
NetworkUtil = "nightcycle/network-util@1.6.0"
Signal = "nightcycle/signal@1.0.2"
HashUtil = "boatbomber/hashlib@1.0.0"